### ISSUE TITLE
Inference Issue: Missing MHT Weights in NeuralPLexer Checkpoint

### ISSUE THREAD

**Issue by JohnBrown2022** [zrqiao/NeuralPLexer#14]
**Environment:**
- **Python Version:** 3.9.18
- **Operating System:** Linux

**Issue Description:**
I was performing batched structure sampling using the NeuralPLexer model checkpoint (version v2, published December 13, 2023) from Zenodo. The inference command (no template) was as follows:

```shell
python NeuralPLexer-main/neuralplexer/inference.py --task=batched_structure_sampling --input-receptor "opt.pdb" --input-ligand "test.sdf" --out-path "test" --model-checkpoint "neuralplexermodels_downstream_datasets_predictions/models/complex_structure_prediction.ckpt" --n-samples 16 --chunk-size 4 --num-steps=40 --cuda --sampler=langevin_simulated_annealing
```

**Encountered Issue:**
The process emitted an error indicating the inability to load pretrained MHT weights, suggesting their absence from the `complex_structure_prediction.ckpt` file, which seems essential for the `_resolve_ligand_encoder` during inference.

```plaintext
...
Could not load pretrained MHT weights, skipping 
...
```

**Investigative Steps:**
To assess the importance of MHT weights for the inference process, I added a debug line in `wrappers.py` (line 470):

```python
        # Assuming static ligand graph
        if "lig_atom_attr" not in batch["features"].keys():
            print("!!!!!!")
            self._initialize_ligand_embeddings(batch)
        return batch
```

This modification confirmed the critical role of MHT weights in the inference.

**Request for Assistance:**
Has anyone else faced a similar issue with missing MHT weights during NeuralPLexer inference? I am looking for any advice or workaround to address this problem. Any shared experiences or suggestions would be highly appreciated.

[output_log.txt](https://github.com/zrqiao/NeuralPLexer/files/14484048/output_log.txt)

**Comment by BigMary2001** [comment]
Do you know where the file "neuralplexermodels_downstream_datasets_predictions" is? I can't find it in the repository.

**Comment by ssalaniwal** [comment]
I ran into the same issue as reported by JohnBrown2022. Any help on this would be greatly appreciated. Thanks in advance.

**Comment by amorehead** [comment]
This issue seems related to https://github.com/zrqiao/NeuralPLexer/issues/3, no?

**Comment by amorehead** [comment]
I believe my new [PR](https://github.com/zrqiao/NeuralPLexer/pull/21) resolves this warning. However, I believe NeuralPLexer still loads the pretrained MHT weights (in spite of this warning being logged) since the `inference.py` calls Lightning's `load_checkpoint()` function without enforcing strict matching of key names. I suspect this issue originally came from the names of the ligand and protein encoder modules being changed in the released source code after the `complex_structure_prediction.ckpt` weights were initially changed.

**Comment by DantongWang** [comment]
> I believe my new [PR](https://github.com/zrqiao/NeuralPLexer/pull/21) resolves this warning. Nonetheless, I believe NeuralPLexer still correctly loads the pretrained MHT weights during inference (in spite of this warning being logged) since the `neuralplexer/inference.py` script calls Lightning's `load_from_checkpoint()` function without enforcing strict matching of key names.
> 
> https://github.com/zrqiao/NeuralPLexer/blob/301f10de0d214c73956b374fc384c0d37ddbf544/neuralplexer/inference.py#L631
> 
> I suspect this issue originally came from the names of the ligand and protein encoder modules being changed in the released source code after the `complex_structure_prediction.ckpt` weights were initially changed. In which case, this is an easy fix.

I also ran into this issue. I downloaded the package last week, thus hopefully this PR is already included. Would this warning affect any of its predictions? Thank you in advance!
