### ISSUE TITLE
How to fix the protein structure (like in the paper's PDBBind experiments)?

### ISSUE THREAD

**Issue by amorehead** [zrqiao/NeuralPLexer#16]
Hello.

Thank you again for making this code open-source. I was curious how one might, for new complexes, simulate the fixed-protein ligand docking experiments in the paper by predicting a ligand structure interacting with a fixed protein structure. Does the inference script support this use case (i.e., where the protein structure will not be generated)? After looking through the code, I could not identify a single CLI argument that controls whether the protein is fixed or not.

Best,
Alex

**Comment by AlvinLeopold** [comment]
Hi amore, I wonder how you handle this question. Actually, I could get two separate files of the protein and the receptor, and I was curious how do you combine the two for downstream analysis.

Any response would be helpful!
cheers

**Comment by amorehead** [comment]
Hi, @AlvinLeopold. Please see the [`PoseBench`](https://github.com/BioinfoMachineLearning/PoseBench) DL benchmark I curated, which includes NeuralPLexer for inference and downstream analysis.
