### ISSUE TITLE
Error trying to install on Debian 12 with cuda 11.8

### ISSUE THREAD

**Issue by syntesys87** [zrqiao/NeuralPLexer#18]
* Python version: 3.11.2 (installed from debian repo)
* Operating System: Debian 12

### Description

After launch 'make environment' in a Debian 12 with CUDA 11.8, I receive the following error:
RuntimeError:
      The detected CUDA version (11.8) mismatches the version that was used to compile
      PyTorch (12.1). Please make sure to use the same CUDA versions.

I cannot change CUDA version, I need it for other software.

### What I Did

git clone
make environment

**Comment by syntesys87** [comment]
Trying to install in Debian 12 with CUDA 12.1 I receive this error:
miniconda/envs/neuralplexer_dev/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4:2: error: #error C++17 or later compatible compiler is required to use PyTorch.

I have cpp-12, gcc-12 and c++-12 installed on system.

**Comment by huohuoxi** [comment]
it is possible to install different versions of Cuda in one system.
If you want to change versions, just change .bashrc
you can search for related tutorials on this.

**Comment by AlvinLeopold** [comment]
CUDA 11.7 + Pytorch 1.13.1 is worked. You could try `conda install -c "nvidia/label/cuda-11.7.1" cuda-toolkit` to address problem with CUDA.
Beside dont forget install PyTorch Scatter which complie with  G++ <= 11 and GCC <= 11.

**Comment by huohuoxi** [comment]
> CUDA 11.7 + Pytorch 1.13.1 is work for me. You could try `conda install -c "nvidia/label/cuda-11.7.1" cuda-toolkit` to address problem with CUDA. Besides dont forget install PyTorch Scatter which complie with G++ <= 11 and GCC <= 11.

Could you please give more specific steps of it? I use "make environment" and it automatically installed every package for me except CUDA. Do you mean that you installed pytorch manually? Thank you very much.

**Comment by AlvinLeopold** [comment]
You will get a conda environment named <neuralplexer_dev> when `make enviroment` was run properly. (If not, please check 'We recommend setting up the [libmambda solver for conda](https://www.anaconda.com/blog/a-faster-conda-for-a-growing-community) before installation.')

Then `conda activate neuralplexer_dev`.

It normally return error after `make environment` , so u may need manually install 

<pytorch 1.13.1> 
run `conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 pytorch-cuda=11.7 -c pytorch -c nvidia`

<torch scatter>
`pip install torch-scatter -f https://data.pyg.org/whl/torch-2.1.0+cu117.html`

<openfold> 
`git clone https://github.com/aqlaboratory/openfold.git`
`cd openfold && sed -i 's/std14/std=c++17/g' setup.py`
`pip install .`

<pytorch3d> 
`git clone https://github.com/facebookresearch/pytorch3d.git
cd pytorch3d && pip install -e --force-reinstall --no-deps .`

At the end, use `bash benchmark_tiny.sh` check which part you need then pip install it.

**Comment by syntesys87** [comment]
Resolved editing the following:

environment _dev.yaml
`name: neuralplexer_dev
channels:
  - nvidia
  - pytorch
  - pytorch3d
  - pyg
  - bioconda
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pytorch=1.13.1
  - pytorch-cuda
  - biopython
  - prody
  - deprecated
  - hydra-core=1.1.1
  - dm-tree
  - ml-collections
  - networkx
  - pypdb
  - pytest
  - dataclasses
  - msgpack-python
  - msgpack-numpy
  - numpy
  - openbabel
  - pandas
  - pytorch3d
  - rdkit
  - rmsd
  - tmalign
  - tensorboard
  - jupyter
  - tqdm
  - python-lmdb
  - vim
  - wandb
  - pip:
    - -r requirements.txt`

requirements.txt
`pytorch-lightning <2.0.0
torch-scatter==2.1.0
torchvision==0.14.1
fairscale
mendeleev
DLLogger @ git+https://github.com/NVIDIA/dllogger.git@0540a43971f4a8a16693a9de9de73c1072020769
openfold @ git+https://github.com/aqlaboratory/openfold.git@103d0370ad9ce07579c20fa9c889a632f9b16618
power-spherical @ git+https://git@github.com/zrqiao/power_spherical.git@290b1630c5f84e3bb0d61711046edcf6e47200d4
fair-esm @ git+https://github.com/facebookresearch/esm@57da016e5d740a9ac5bcf62c3689a42e88584bc
seaborn`

Before the `make install`, launch the command `conda activate neuralplexer_dev`.

**Comment by syntesys87** [comment]
``
