### ISSUE TITLE
Sementation fault

### ISSUE THREAD

**Issue by Toverkwark** [zrqiao/NeuralPLexer#2]
* PIGT version:
* Python version:3.10.13
* Operating System:Debian 10

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

Any way I try to run neuralplexer-inferece, whether in an individual command or through the benchmark_tiny.sh script, I get a segmentation fault error without further information.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```
neuralplexer-inference --task=batched_structure_sampling --input-receptor ../test.pdb --input-ligand ../test.sdf --out-path ../testoutput --model-checkpoint ../complex_structure_prediction.ckpt --n-samples 16 --chunk-size 4 --num-steps=40 --cuda --sampler=langevin_simulated_annealing

**Comment by MKCarter** [comment]
I would re-install your environment using these instructions - https://github.com/zrqiao/NeuralPLexer/issues/1#issuecomment-1943617144 - this should pin the correct python, torch, torchvision, and torch-scatter versions that are needed to have a working environment. 

Hope that works!
