### ISSUE TITLE
Huge protein issue

### ISSUE THREAD

**Issue by AlvinLeopold** [zrqiao/NeuralPLexer#23]
Hey everyone,

Big thanks to all the developers out there making strides in protein-ligand prediction. Your work is super appreciated!

I've hit a snag with GPU memory running out while working on larger receptor proteins. I'm thinking about splitting the proteins into three parts to manage this. Do you think this could mess with the accuracy of the predictions? Any thoughts or workarounds would be really helpful.

Cheers for any advice you can share!

**Comment by amorehead** [comment]
Have you tried setting `chunk_size=4` instead of the default value of `10`?
