### ISSUE TITLE
Can I load .pt file without having to download it?

### ISSUE THREAD

**Issue by DantongWang** [zrqiao/NeuralPLexer#38]
* Python version: 3.8.16
* Operating System: Kylin V10
* torch version: 1.11

### Description
I tried to run the command as pasted below and was stuck at the stage: Downloading: "https://dl.fbaipublicfiles.com/fair-esm/models/esm2_t33_650M_UR50D.pt". 
Now I have downloaded the file "esm2_t33_650M_UR50D.pt". So is there a way that I can ask NeuralPlexer to load the model directly without trying to download it again?

### What I Did

```
neuralplexer-inference --task=batched_structure_sampling --sampler=langevin_simulated_annealing --input-receptor /home/wangdantong/5xh3.pdb --input-ligand /home/wangdantong/substrate_structures/MHET.sdf --out-path /home/wangdantong/output/ --model-checkpoint complex_structure_prediction.ckpt.
```

**Comment by Nireus-lgx** [comment]
hi, i also have this question. Now, have you solve this problem?

**Comment by Nireus-lgx** [comment]
> * Python version: 3.8.16
> * Operating System: Kylin V10
> * torch version: 1.11
> 
> ### Description
> I tried to run the command as pasted below and was stuck at the stage: Downloading: "https://dl.fbaipublicfiles.com/fair-esm/models/esm2_t33_650M_UR50D.pt". Now I have downloaded the file "esm2_t33_650M_UR50D.pt". So is there a way that I can ask NeuralPlexer to load the model directly without trying to download it again?
> 
> ### What I Did
> ```
> neuralplexer-inference --task=batched_structure_sampling --sampler=langevin_simulated_annealing --input-receptor /home/wangdantong/5xh3.pdb --input-ligand /home/wangdantong/substrate_structures/MHET.sdf --out-path /home/wangdantong/output/ --model-checkpoint complex_structure_prediction.ckpt.
> ```

You can manually download  esm2_t33_650M_UR50D.pt and copy the model file into /root/.cache/torch/hub/checkpoints/.

**Comment by DantongWang** [comment]
> > * Python version: 3.8.16
> > * Operating System: Kylin V10
> > * torch version: 1.11
> > 
> > ### Description
> > I tried to run the command as pasted below and was stuck at the stage: Downloading: "https://dl.fbaipublicfiles.com/fair-esm/models/esm2_t33_650M_UR50D.pt". Now I have downloaded the file "esm2_t33_650M_UR50D.pt". So is there a way that I can ask NeuralPlexer to load the model directly without trying to download it again?
> > ### What I Did
> > ```
> > neuralplexer-inference --task=batched_structure_sampling --sampler=langevin_simulated_annealing --input-receptor /home/wangdantong/5xh3.pdb --input-ligand /home/wangdantong/substrate_structures/MHET.sdf --out-path /home/wangdantong/output/ --model-checkpoint complex_structure_prediction.ckpt.
> > ```
> 
> You can manually download esm2_t33_650M_UR50D.pt and copy the model file into /root/.cache/torch/hub/checkpoints/.

It works for me now, thank you for the help!
