### ISSUE TITLE
structure not refined, and no pLDDT output.

### ISSUE THREAD

**Issue by Samuel-gwb** [zrqiao/NeuralPLexer#8]
When I execute following script to run neuralplexer:
neuralplexer-inference --task=batched_structure_sampling \
                       --input-receptor PDI/Dom34.pdb \
                       --input-ligand PDI/ligand.sdf \
                       --out-path PDI/pdi \
                       --model-checkpoint data/models/complex_structure_prediction.ckpt \
                       --n-samples 16 \
                       --chunk-size 4 \
                       --num-steps=40 \
                       --cuda \
                       --sampler=langevin_simulated_annealing

It outputs a complex structure ensemble containing 16 docking results. 
However, most of the complex structures contain conflicts between ligand and protein. 
1) Is any option or method to be added/integrated into the neuralplexer to do energy minization, as in AF2?
2) As mentioned by @jsture, the result pdbs do not write pLDDT, either.

**Comment by zrqiao** [comment]
Thanks for submitting the issue!
While these functionalities are out of the scope of this academic release, we highly welcome community contributions for such features to facilitate further research. We are willing to perform code reviews if a PR is ready.

**Comment by Samuel-gwb** [comment]
I have following output warnings addition to MHT weights problem, and does publically provided weight parameters support plddt calculation if try code modification?

/miniconda3/envs/neuralplexer/lib/python3.9/site-packages/pytorch_lightning/core/saving.py:251: UserWarning: Found keys that are in the model state dict but not in the checkpoint: ['atnum2vdw_uff', 'plm.embed_tokens.weight', 'plm.layers.0.self_attn.k_proj.weight', 'plm.layers.0.self_attn.k_proj.bias', 'plm.layers.0.self_attn.v_proj.weight', 'plm.layers.0.self_attn.v_proj.bias', ... ...
